version: "3.9"
services:
  db:
    build:
      context: ./backend
      dockerfile: ./docker/db/Dockerfile
    container_name: secret_santa_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    networks:
      - backend-network

  api:
    build:
      context: ./backend
      dockerfile: ./docker/api/Dockerfile
    container_name: secret_santa_api
    restart: always
    ports:
      - "8080:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/src/dist
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - db

  web:
    build:
      context: ./frontend
      dockerfile: ./docker/web/Dockerfile
    container_name: secret_santa_web
    ports:
      - "3000:3000"
    # Only in development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
